services:
  - type: web
    name: aletrack-api-dev
    runtime: docker
    plan: free
    branch: dev
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: ASPNETCORE_URLS
        value: http://*:$PORT
      - key: ConnectionStrings__AleTrack
        value: Data Source=Infrastructure/Persistence/aletrack.db
        
    disk:
      name: aletrack-data
      mountPath: /data
      sizeGB: 1